-- JalNetra BigQuery Schema
-- Cloud-tier aggregation and analytics tables
-- Partitioned by day for cost-efficient time-series queries

-- Dataset
-- CREATE SCHEMA IF NOT EXISTS jalnetra OPTIONS(location = 'asia-south1');

-- Sensor readings from all edge gateways
CREATE TABLE IF NOT EXISTS jalnetra.sensor_readings (
    gateway_id      STRING      NOT NULL,
    node_id         STRING      NOT NULL,
    timestamp       TIMESTAMP   NOT NULL,
    tds             FLOAT64,
    ph              FLOAT64,
    turbidity       FLOAT64,
    dissolved_oxygen FLOAT64,
    flow_rate       FLOAT64,
    water_level     FLOAT64,
    battery_pct     INT64,
    rssi_dbm        INT64,
    anomaly_label   STRING,         -- normal | contamination | sensor_fault
    anomaly_confidence FLOAT64,
    ingested_at     TIMESTAMP   NOT NULL
)
PARTITION BY DATE(timestamp)
CLUSTER BY gateway_id, node_id
OPTIONS(
    description = 'Sensor readings from all JalNetra edge gateways',
    require_partition_filter = true
);

-- Alerts generated by edge inference
CREATE TABLE IF NOT EXISTS jalnetra.alerts (
    gateway_id      STRING      NOT NULL,
    alert_id        STRING      NOT NULL,
    node_id         STRING      NOT NULL,
    severity        STRING      NOT NULL,   -- INFO | WARNING | CRITICAL | EMERGENCY
    alert_type      STRING      NOT NULL,   -- contamination | sensor_fault | depletion | threshold
    message         STRING,
    parameter       STRING,
    value           FLOAT64,
    threshold       FLOAT64,
    created_at      TIMESTAMP   NOT NULL,
    acknowledged_at TIMESTAMP,
    ingested_at     TIMESTAMP   NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY gateway_id, severity
OPTIONS(
    description = 'Alerts from all JalNetra edge gateways'
);

-- ML predictions synced from edge
CREATE TABLE IF NOT EXISTS jalnetra.predictions (
    gateway_id      STRING      NOT NULL,
    node_id         STRING      NOT NULL,
    prediction_type STRING      NOT NULL,   -- anomaly | depletion | irrigation
    predicted_at    TIMESTAMP   NOT NULL,
    horizon_days    INT64,
    prediction_json STRING,                 -- Full prediction payload as JSON
    confidence      FLOAT64,
    ingested_at     TIMESTAMP   NOT NULL
)
PARTITION BY DATE(predicted_at)
CLUSTER BY gateway_id, prediction_type
OPTIONS(
    description = 'ML predictions from edge inference engines'
);

-- Sync log for idempotency and auditing
CREATE TABLE IF NOT EXISTS jalnetra.sync_log (
    batch_id        STRING      NOT NULL,
    gateway_id      STRING      NOT NULL,
    readings_count  INT64,
    alerts_count    INT64,
    raw_archive_path STRING,
    synced_at       TIMESTAMP   NOT NULL
)
PARTITION BY DATE(synced_at)
OPTIONS(
    description = 'Edge-to-cloud sync audit log'
);

-- Materialized view: Latest reading per node (for dashboard)
CREATE MATERIALIZED VIEW IF NOT EXISTS jalnetra.latest_readings AS
SELECT
    gateway_id,
    node_id,
    ARRAY_AGG(
        STRUCT(timestamp, tds, ph, turbidity, dissolved_oxygen, flow_rate, water_level, battery_pct, rssi_dbm, anomaly_label)
        ORDER BY timestamp DESC LIMIT 1
    )[OFFSET(0)] AS latest
FROM jalnetra.sensor_readings
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
GROUP BY gateway_id, node_id;

-- View: Daily water quality summary per gateway
CREATE OR REPLACE VIEW jalnetra.daily_quality_summary AS
SELECT
    gateway_id,
    DATE(timestamp) AS date,
    COUNT(*) AS total_readings,
    AVG(tds) AS avg_tds,
    AVG(ph) AS avg_ph,
    AVG(turbidity) AS avg_turbidity,
    AVG(dissolved_oxygen) AS avg_do,
    COUNTIF(anomaly_label = 'contamination') AS contamination_count,
    COUNTIF(anomaly_label = 'sensor_fault') AS sensor_fault_count,
    COUNTIF(tds > 500) AS tds_exceedance_count,
    COUNTIF(ph < 6.5 OR ph > 8.5) AS ph_exceedance_count,
    COUNTIF(turbidity > 5) AS turbidity_exceedance_count
FROM jalnetra.sensor_readings
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 90 DAY)
GROUP BY gateway_id, DATE(timestamp);

-- View: JJM compliance report
CREATE OR REPLACE VIEW jalnetra.jjm_compliance AS
SELECT
    gateway_id,
    DATE(timestamp) AS date,
    COUNT(DISTINCT node_id) AS active_nodes,
    ROUND(COUNTIF(
        tds <= 500 AND ph BETWEEN 6.5 AND 8.5 AND turbidity <= 1
    ) * 100.0 / COUNT(*), 1) AS compliance_pct,
    ROUND(AVG(tds), 1) AS avg_tds,
    ROUND(AVG(ph), 2) AS avg_ph,
    ROUND(AVG(turbidity), 2) AS avg_turbidity
FROM jalnetra.sensor_readings
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)
GROUP BY gateway_id, DATE(timestamp);
